# ------------------------------------------------------------------------------
#          NOTE: THIS DOCKERFILE IS GENERATED BY OCI IMAGES PROJECT
#
#                       PLEASE DO NOT EDIT IT DIRECTLY.
# ------------------------------------------------------------------------------
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#https://github.com/adoptium/temurin17-binaries/releases/download/jdk-17.0.4%2B8/OpenJDK17U-jre_aarch64_linux_hotspot_17.0.4_8.tar.gz

FROM registry.access.redhat.com/ubi8/ubi-minimal:8.6

ENV LANG='en_US.UTF-8' LANGUAGE='en_US:en' LC_ALL='en_US.UTF-8'

EXPOSE 8080 8443 8778

RUN microdnf install -y tzdata openssl curl ca-certificates fontconfig glibc-langpack-en gzip tar \
    && microdnf update -y; microdnf clean all

LABEL name="ubi-jre17-minimal" \
      vendor="Oci-Images-Project" \
      version="jdk-17.0.4+8" \
      release="17" \
      run="docker run --rm -ti <image_name:tag> /bin/bash" \
      summary="Adoptium Temurin  OCI Image for OpenJDK with hotspot and ubi-minimal for runs Java applications" \
      description="For more information on this image please see https://github.com/DemonAzteck/oci-images/tree/main/java/runner"

ENV JAVA_VERSION jdk-17.0.4+8

RUN set -eux; \
    ARCH="$(uname -m)"; \
    case "${ARCH}" in \
       aarch64|arm64) \
         ESUM='d0fc84cb9627641d5a3c85aef9e7e26e4874e37524f9425112c6def5b12b7892'; \
         BINARY_URL='https://github.com/adoptium/temurin17-binaries/releases/download/jdk-17.0.4%2B8/OpenJDK17U-jre_aarch64_linux_hotspot_17.0.4_8.tar.gz'; \
         ;; \
       ppc64el|ppc64le) \
         ESUM='a5d055cbdb1f8ef537afc66a6315e865646305420cb96ab08dc239074f88ad1d'; \
         BINARY_URL='https://github.com/adoptium/temurin17-binaries/releases/download/jdk-17.0.4%2B8/OpenJDK17U-jre_ppc64le_linux_hotspot_17.0.4_8.tar.gz'; \
         ;; \
       amd64|x86_64) \
         ESUM='616b137b87fa84211ac2f5c23dfcf3a8c5df9d0fd7ea3c872a0bf394b2f6c464'; \
         BINARY_URL='https://github.com/adoptium/temurin17-binaries/releases/download/jdk-17.0.4%2B8/OpenJDK17U-jre_x64_linux_hotspot_17.0.4_8.tar.gz'; \
         ;; \
       *) \
         echo "Unsupported arch: ${ARCH}"; \
         exit 1; \
         ;; \
    esac; \
    curl -kLfsSo /tmp/openjdk.tar.gz ${BINARY_URL}; \
    echo "${ESUM} */tmp/openjdk.tar.gz" | sha256sum -c -; \
    mkdir -p /opt/java/openjdk; \
	mkdir -p /opt/app; \
    cd /opt/java/openjdk; \
    tar -xf /tmp/openjdk.tar.gz --strip-components=1; \
    rm -rf /tmp/openjdk.tar.gz;
COPY java_runner.sh /opt/app
ENV JAVA_HOME=/opt/java/openjdk \
	JAVA_OPTIONS=\
	JAVA_ARGS=\
    PATH="/opt/java/openjdk/bin:$PATH"
RUN echo Verifying install ... \
    && echo java --version && java --version \
    && echo Complete.
WORKDIR /opt/app
COPY java_runner.sh /opt/app
RUN chown 1001 /opt/app; \
    chmod "g+rwX" /opt/app; \
    chown 1001:root /opt/app; \
	chown 1001 /opt/app/java_runner.sh;  \
    chmod 540 /opt/app/java_runner.sh;
USER 1001
CMD ["/bin/bash","/opt/app/java_runner.sh","run"]
